verticles:
  dao: pt.fabm.template.dao.DaoVerticle
  rest: pt.fabm.template.rest.RestVerticle
confs:
  rest:
    host: 0.0.0.0
    pdir: ./frontend/dist
    #user token timeout in milliseconds 30 minutes = 30*60*1000
    user_timeout: 1.800.000
