verticles:
  dao: pt.fabm.template.dao.DaoVerticle
  rest: pt.fabm.template.rest.RestVerticle
confs:
  rest:
    #user token timeout in milliseconds
    user_timeout: 1000
    host: localhost
    pdir: @pdir@
  dao:
    host: 0.0.0.0
    port: 8081

